### ISSUE TITLE
sensor extrinsic params

### ISSUE THREAD

**Issue by chengwei0427** [sjtuyinjie/Ground-Challenge#2]
Hi, @sjtuyinjie 

Nice work. Can you upload the config params (extrinsic params)?

Thanks.

**Comment by sjtuyinjie** [comment]
I'd like to, but considering that this paper is still under review, I may not upload calibration files recently.

**Comment by sjtuyinjie** [comment]
You can refer to M2DGR for the intrinsic parameter of D435I, which is quite similar to parameters in this work. But I am not permitted to give you the files now officially.

**Comment by chengwei0427** [comment]
Thanks for your reply.

But I'd like to test my LIO with lidar,imu and wheel odom.

So extrinsic params is needed.

**Comment by sjtuyinjie** [comment]
Just try the identify matrix. The frames of these three sensors are all xyz to left-front-up



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 15, 2022 10:06 AM
To: ***@***.***&gt;;
Cc: "Yin ***@***.******@***.***&gt;;
Subject: Re: [sjtuyinjie/Ground-Challenge] sensor extrinsic params (Issue #2)




 
Thanks for your reply.
 
But I'd like to test my LIO with lidar,imu and wheel odom.
 
So extrinsic params is needed.

**Comment by chengwei0427** [comment]
Thanks for your reply.

My problem is solved, and I'll close the issue.

**Comment by srinivasrama** [comment]
@chengwei0427 are you manage to fuse wheel odom with LIO system? If so, can you share some reference

**Comment by chengwei0427** [comment]
Hi， @srinivasrama 

A simple method, you can add a factor like this: res = V_predict-V_m;

Furthermore, you can have a look at "VINS on wheels".

**Comment by zsy0817** [comment]
> Thanks for your reply.
> 
> My problem is solved, and I'll close the issue.

Hello, how do you set the extrinsic params between the lidar and IMU?

**Comment by chengwei0427** [comment]
@zsy0817 

> Just try the identify matrix. The frames of these three sensors are all xyz to left-front-up
> […](#)

Just try the identify matrix.
