### ISSUE TITLE
Download link of slope1 sequence is conflict with static2 sequence

### ISSUE THREAD

**Issue by xiaobrnbrn** [sjtuyinjie/Ground-Challenge#3]
Thanks a lot for your datasets. The download link of slope1 sequence is conflict with static2 sequence, please update the download link of slope1.

**Comment by sjtuyinjie** [comment]
Already updated. Welcome to test our dataset



---Original---
From: "Si ***@***.***&gt;
Date: Mon, Jul 17, 2023 20:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [sjtuyinjie/Ground-Challenge] Download link of slope1 sequence isconflict with static2 sequence (Issue #3)




 
Thanks a lot for your datasets. The download link of slope1 sequence is conflict with static2 sequence, please update the download link of slope1.

**Comment by sjtuyinjie** [comment]
Cite the provided link please if the dataset is helpful for your research
